name: Run tests
on:
  push:
    branches: master

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Configure java version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build and test artifacts
        run: scripts/build_and_test_jars.sh

      - name: Upload playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-results
          path: playwright-results
